version: '3.8'

services:
  web:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis
      - db

  redis:
    image: redis:7

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: converter

  celery:
    build: ./backend
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/code
    env_file: .env
    depends_on:
      - web
      - redis