# Generated by Django 5.2.4 on 2025-07-25 15:46

import converter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_conversionjob_session_id_mediafile_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionjob',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='converted_file',
            field=models.FileField(blank=True, null=True, upload_to=converter.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=converter.models.user_directory_path),
        ),
    ]
