# Generated by Django 5.2.4 on 2025-07-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_conversionjob_error_message_conversionjob_is_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=40, unique=True)),
            ],
        ),
    ]
