# Generated by Django 5.2.4 on 2025-07-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_session_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session_Id',
        ),
    ]
